# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/settings_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(689, 511)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layout = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layout.sizePolicy().hasHeightForWidth())
        self.layout.setSizePolicy(sizePolicy)
        self.layout.setMaximumSize(QtCore.QSize(150, 16777215))
        self.layout.setObjectName("layout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layout)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settings_menu_list = QtWidgets.QListWidget(self.layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_menu_list.sizePolicy().hasHeightForWidth())
        self.settings_menu_list.setSizePolicy(sizePolicy)
        self.settings_menu_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.settings_menu_list.setStyleSheet("QListWidget::item { border-bottom: 1px solid black; }\n"
"QListWidget::item:selected:active {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #4e55c6, stop: 1 #888dd9);\n"
"}\n"
"QListWidget:item:selected:!active {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #4e55c6, stop: 1 #888dd9);\n"
"    color: white\n"
"}\n"
"QListWidget::item {\n"
"    height: 50;\n"
"}")
        self.settings_menu_list.setProperty("isWrapping", False)
        self.settings_menu_list.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.settings_menu_list.setViewMode(QtWidgets.QListView.ListMode)
        self.settings_menu_list.setUniformItemSizes(False)
        self.settings_menu_list.setBatchSize(200)
        self.settings_menu_list.setWordWrap(True)
        self.settings_menu_list.setSelectionRectVisible(False)
        self.settings_menu_list.setObjectName("settings_menu_list")
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.settings_menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.settings_menu_list.addItem(item)
        self.verticalLayout_2.addWidget(self.settings_menu_list)
        self.horizontalLayout.addWidget(self.layout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settings_stackedwidget = QtWidgets.QStackedWidget(self.frame)
        self.settings_stackedwidget.setObjectName("settings_stackedwidget")
        self.network_variables_page = QtWidgets.QWidget()
        self.network_variables_page.setObjectName("network_variables_page")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.network_variables_page)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.netvars_table = QtWidgets.QTableView(self.network_variables_page)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.netvars_table.setFont(font)
        self.netvars_table.setObjectName("netvars_table")
        self.horizontalLayout_4.addWidget(self.netvars_table)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.add_row_button = QtWidgets.QPushButton(self.network_variables_page)
        self.add_row_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_row_button.setIcon(icon)
        self.add_row_button.setObjectName("add_row_button")
        self.verticalLayout_7.addWidget(self.add_row_button)
        self.delete_row_button = QtWidgets.QPushButton(self.network_variables_page)
        self.delete_row_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_row_button.setIcon(icon1)
        self.delete_row_button.setObjectName("delete_row_button")
        self.verticalLayout_7.addWidget(self.delete_row_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.settings_stackedwidget.addWidget(self.network_variables_page)
        self.step_parameters_page = QtWidgets.QWidget()
        self.step_parameters_page.setObjectName("step_parameters_page")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.step_parameters_page)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fixed_range_groupbox = QtWidgets.QGroupBox(self.step_parameters_page)
        self.fixed_range_groupbox.setObjectName("fixed_range_groupbox")
        self.edit_fixed_step_widget_layout = QtWidgets.QVBoxLayout(self.fixed_range_groupbox)
        self.edit_fixed_step_widget_layout.setObjectName("edit_fixed_step_widget_layout")
        self.horizontalLayout_3.addWidget(self.fixed_range_groupbox)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.step_parameters_page)
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_5.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.exact_step_spinbox = QtWidgets.QDoubleSpinBox(self.verticalGroupBox_2)
        self.exact_step_spinbox.setDecimals(3)
        self.exact_step_spinbox.setMaximum(100.0)
        self.exact_step_spinbox.setProperty("value", 0.002)
        self.exact_step_spinbox.setObjectName("exact_step_spinbox")
        self.verticalLayout_5.addWidget(self.exact_step_spinbox)
        self.label_2 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.common_step_spinbox = QtWidgets.QDoubleSpinBox(self.verticalGroupBox_2)
        self.common_step_spinbox.setDecimals(3)
        self.common_step_spinbox.setMaximum(100.0)
        self.common_step_spinbox.setProperty("value", 0.05)
        self.common_step_spinbox.setObjectName("common_step_spinbox")
        self.verticalLayout_5.addWidget(self.common_step_spinbox)
        self.label_3 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.rough_step_spinbox = QtWidgets.QDoubleSpinBox(self.verticalGroupBox_2)
        self.rough_step_spinbox.setDecimals(3)
        self.rough_step_spinbox.setMaximum(100.0)
        self.rough_step_spinbox.setProperty("value", 0.5)
        self.rough_step_spinbox.setObjectName("rough_step_spinbox")
        self.verticalLayout_5.addWidget(self.rough_step_spinbox)
        self.disable_scroll_on_table_checkbox = QtWidgets.QCheckBox(self.verticalGroupBox_2)
        self.disable_scroll_on_table_checkbox.setChecked(False)
        self.disable_scroll_on_table_checkbox.setObjectName("disable_scroll_on_table_checkbox")
        self.verticalLayout_5.addWidget(self.disable_scroll_on_table_checkbox)
        self.mouse_inversion_checkbox = QtWidgets.QCheckBox(self.verticalGroupBox_2)
        self.mouse_inversion_checkbox.setObjectName("mouse_inversion_checkbox")
        self.verticalLayout_5.addWidget(self.mouse_inversion_checkbox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.verticalGroupBox_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(9, 6, 9, 6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.step_parameters_page)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.start_deviation_spinbox = QtWidgets.QSpinBox(self.step_parameters_page)
        self.start_deviation_spinbox.setMaximum(100)
        self.start_deviation_spinbox.setProperty("value", 5)
        self.start_deviation_spinbox.setObjectName("start_deviation_spinbox")
        self.verticalLayout_6.addWidget(self.start_deviation_spinbox)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.settings_stackedwidget.addWidget(self.step_parameters_page)
        self.verticalLayout.addWidget(self.settings_stackedwidget)
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.save_and_exit_button = QtWidgets.QPushButton(Dialog)
        self.save_and_exit_button.setAutoDefault(True)
        self.save_and_exit_button.setObjectName("save_and_exit_button")
        self.horizontalLayout_2.addWidget(self.save_and_exit_button)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setAutoDefault(False)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.save_button = QtWidgets.QPushButton(Dialog)
        self.save_button.setAutoDefault(True)
        self.save_button.setDefault(True)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_2.addWidget(self.save_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        self.settings_menu_list.setCurrentRow(-1)
        self.settings_stackedwidget.setCurrentIndex(0)
        self.settings_menu_list.currentRowChanged['int'].connect(self.settings_stackedwidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки"))
        self.settings_menu_list.setSortingEnabled(False)
        __sortingEnabled = self.settings_menu_list.isSortingEnabled()
        self.settings_menu_list.setSortingEnabled(False)
        item = self.settings_menu_list.item(0)
        item.setText(_translate("Dialog", "Сетевые переменные"))
        item = self.settings_menu_list.item(1)
        item.setText(_translate("Dialog", "Параметры шага"))
        self.settings_menu_list.setSortingEnabled(__sortingEnabled)
        self.fixed_range_groupbox.setTitle(_translate("Dialog", "Фиксированный шаг"))
        self.verticalGroupBox_2.setWhatsThis(_translate("Dialog", "Относительный шаг устанавливается в процентах от максимума шкалы поверяемого прибора"))
        self.verticalGroupBox_2.setTitle(_translate("Dialog", "Относительный шаг"))
        self.label.setText(_translate("Dialog", "Точный, %"))
        self.label_2.setText(_translate("Dialog", "Обычный, %"))
        self.label_3.setText(_translate("Dialog", "Грубый, %"))
        self.disable_scroll_on_table_checkbox.setText(_translate("Dialog", "Отключить прокрутку шага,\n"
"если курсор мыши находится\n"
"на таблице измерения"))
        self.mouse_inversion_checkbox.setText(_translate("Dialog", "Инвертировать\n"
"колесо мыши"))
        self.label_4.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Во время измерения, при нажатии кнопки &quot;Перейти к точке&quot;, на калибраторе будет установлено значение: </p><p>&quot;выбранная точка +(-) начальное отклонение&quot;. </p><p>Начальное отклонение задается в процентах от максимума шкалы поверяемого прибора.</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "Начальное отклонение, %"))
        self.save_and_exit_button.setText(_translate("Dialog", "Ок"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))
        self.save_button.setText(_translate("Dialog", "Принять"))
import icons_rc
