# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_form.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(672, 526)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layout = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layout.sizePolicy().hasHeightForWidth())
        self.layout.setSizePolicy(sizePolicy)
        self.layout.setMaximumSize(QtCore.QSize(150, 16777215))
        self.layout.setObjectName("layout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layout)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settings_menu_list = QtWidgets.QListWidget(self.layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_menu_list.sizePolicy().hasHeightForWidth())
        self.settings_menu_list.setSizePolicy(sizePolicy)
        self.settings_menu_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.settings_menu_list.setStyleSheet("QListWidget::item { border-bottom: 1px solid black; }\n"
"QListWidget::item:selected:active {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #4e55c6, stop: 1 #888dd9);\n"
"}\n"
"QListWidget:item:selected:!active {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #4e55c6, stop: 1 #888dd9);\n"
"    color: white\n"
"}\n"
"QListWidget::item {\n"
"    height: 50;\n"
"}")
        self.settings_menu_list.setProperty("isWrapping", False)
        self.settings_menu_list.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.settings_menu_list.setViewMode(QtWidgets.QListView.ListMode)
        self.settings_menu_list.setUniformItemSizes(False)
        self.settings_menu_list.setBatchSize(200)
        self.settings_menu_list.setWordWrap(True)
        self.settings_menu_list.setSelectionRectVisible(False)
        self.settings_menu_list.setObjectName("settings_menu_list")
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.settings_menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.settings_menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.settings_menu_list.addItem(item)
        self.verticalLayout_2.addWidget(self.settings_menu_list)
        self.horizontalLayout.addWidget(self.layout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settings_stackedwidget = QtWidgets.QStackedWidget(self.frame)
        self.settings_stackedwidget.setObjectName("settings_stackedwidget")
        self.network_variables_page = QtWidgets.QWidget()
        self.network_variables_page.setObjectName("network_variables_page")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.network_variables_page)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.netvars_table = QtWidgets.QTableView(self.network_variables_page)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.netvars_table.setFont(font)
        self.netvars_table.setObjectName("netvars_table")
        self.horizontalLayout_4.addWidget(self.netvars_table)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.add_row_button = QtWidgets.QPushButton(self.network_variables_page)
        self.add_row_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_row_button.setIcon(icon)
        self.add_row_button.setObjectName("add_row_button")
        self.verticalLayout_7.addWidget(self.add_row_button)
        self.delete_row_button = QtWidgets.QPushButton(self.network_variables_page)
        self.delete_row_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_row_button.setIcon(icon1)
        self.delete_row_button.setObjectName("delete_row_button")
        self.verticalLayout_7.addWidget(self.delete_row_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.settings_stackedwidget.addWidget(self.network_variables_page)
        self.aux_tests_settings_page = QtWidgets.QWidget()
        self.aux_tests_settings_page.setObjectName("aux_tests_settings_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.aux_tests_settings_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.aux_tests_settings_page)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setObjectName("label_4")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setObjectName("label_7")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.correction_deviation_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.correction_deviation_spinbox.setObjectName("correction_deviation_spinbox")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.correction_deviation_spinbox)
        self.deviation_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.deviation_spinbox.setObjectName("deviation_spinbox")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.deviation_spinbox)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.groupBox = QtWidgets.QGroupBox(self.aux_tests_settings_page)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.voltage_25_discretes_60v_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.voltage_25_discretes_60v_spinbox.setMaximum(700.0)
        self.voltage_25_discretes_60v_spinbox.setObjectName("voltage_25_discretes_60v_spinbox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.voltage_25_discretes_60v_spinbox)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.voltage_230_discretes_60v_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.voltage_230_discretes_60v_spinbox.setMaximum(700.0)
        self.voltage_230_discretes_60v_spinbox.setObjectName("voltage_230_discretes_60v_spinbox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.voltage_230_discretes_60v_spinbox)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.aux_tests_settings_page)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.voltage_25_discretes_200v_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.voltage_25_discretes_200v_spinbox.setMaximum(700.0)
        self.voltage_25_discretes_200v_spinbox.setObjectName("voltage_25_discretes_200v_spinbox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.voltage_25_discretes_200v_spinbox)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.voltage_230_discretes_200v_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.voltage_230_discretes_200v_spinbox.setMaximum(700.0)
        self.voltage_230_discretes_200v_spinbox.setObjectName("voltage_230_discretes_200v_spinbox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.voltage_230_discretes_200v_spinbox)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.aux_tests_settings_page)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.voltage_25_discretes_600v_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.voltage_25_discretes_600v_spinbox.setMaximum(700.0)
        self.voltage_25_discretes_600v_spinbox.setObjectName("voltage_25_discretes_600v_spinbox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.voltage_25_discretes_600v_spinbox)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.voltage_230_discretes_600v_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.voltage_230_discretes_600v_spinbox.setMaximum(700.0)
        self.voltage_230_discretes_600v_spinbox.setObjectName("voltage_230_discretes_600v_spinbox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.voltage_230_discretes_600v_spinbox)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.aux_tests_settings_page)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.voltage_25_discretes_4v_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.voltage_25_discretes_4v_spinbox.setMaximum(700.0)
        self.voltage_25_discretes_4v_spinbox.setObjectName("voltage_25_discretes_4v_spinbox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.voltage_25_discretes_4v_spinbox)
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.voltage_230_discretes_4v_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.voltage_230_discretes_4v_spinbox.setMaximum(700.0)
        self.voltage_230_discretes_4v_spinbox.setObjectName("voltage_230_discretes_4v_spinbox")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.voltage_230_discretes_4v_spinbox)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.settings_stackedwidget.addWidget(self.aux_tests_settings_page)
        self.step_parameters_page = QtWidgets.QWidget()
        self.step_parameters_page.setObjectName("step_parameters_page")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.step_parameters_page)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.fixed_range_groupbox = QtWidgets.QGroupBox(self.step_parameters_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixed_range_groupbox.sizePolicy().hasHeightForWidth())
        self.fixed_range_groupbox.setSizePolicy(sizePolicy)
        self.fixed_range_groupbox.setObjectName("fixed_range_groupbox")
        self.edit_fixed_step_widget_layout = QtWidgets.QVBoxLayout(self.fixed_range_groupbox)
        self.edit_fixed_step_widget_layout.setObjectName("edit_fixed_step_widget_layout")
        self.horizontalLayout_3.addWidget(self.fixed_range_groupbox)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.step_parameters_page)
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_5.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.exact_step_spinbox = QtWidgets.QDoubleSpinBox(self.verticalGroupBox_2)
        self.exact_step_spinbox.setDecimals(3)
        self.exact_step_spinbox.setMaximum(100.0)
        self.exact_step_spinbox.setProperty("value", 0.002)
        self.exact_step_spinbox.setObjectName("exact_step_spinbox")
        self.verticalLayout_5.addWidget(self.exact_step_spinbox)
        self.label_2 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.common_step_spinbox = QtWidgets.QDoubleSpinBox(self.verticalGroupBox_2)
        self.common_step_spinbox.setDecimals(3)
        self.common_step_spinbox.setMaximum(100.0)
        self.common_step_spinbox.setProperty("value", 0.05)
        self.common_step_spinbox.setObjectName("common_step_spinbox")
        self.verticalLayout_5.addWidget(self.common_step_spinbox)
        self.label_3 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.rough_step_spinbox = QtWidgets.QDoubleSpinBox(self.verticalGroupBox_2)
        self.rough_step_spinbox.setDecimals(3)
        self.rough_step_spinbox.setMaximum(100.0)
        self.rough_step_spinbox.setProperty("value", 0.5)
        self.rough_step_spinbox.setObjectName("rough_step_spinbox")
        self.verticalLayout_5.addWidget(self.rough_step_spinbox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.verticalGroupBox_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.settings_stackedwidget.addWidget(self.step_parameters_page)
        self.verticalLayout.addWidget(self.settings_stackedwidget)
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.save_and_exit_button = QtWidgets.QPushButton(Dialog)
        self.save_and_exit_button.setAutoDefault(True)
        self.save_and_exit_button.setObjectName("save_and_exit_button")
        self.horizontalLayout_2.addWidget(self.save_and_exit_button)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setAutoDefault(False)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.save_button = QtWidgets.QPushButton(Dialog)
        self.save_button.setAutoDefault(True)
        self.save_button.setDefault(True)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_2.addWidget(self.save_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        self.settings_menu_list.setCurrentRow(-1)
        self.settings_stackedwidget.setCurrentIndex(1)
        self.settings_menu_list.currentRowChanged['int'].connect(self.settings_stackedwidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки"))
        self.settings_menu_list.setSortingEnabled(False)
        __sortingEnabled = self.settings_menu_list.isSortingEnabled()
        self.settings_menu_list.setSortingEnabled(False)
        item = self.settings_menu_list.item(0)
        item.setText(_translate("Dialog", "Сетевые переменные"))
        item = self.settings_menu_list.item(1)
        item.setText(_translate("Dialog", "Тесты предварительных стабилизаторов"))
        item = self.settings_menu_list.item(2)
        item.setText(_translate("Dialog", "Параметры шага"))
        self.settings_menu_list.setSortingEnabled(__sortingEnabled)
        self.groupBox_5.setTitle(_translate("Dialog", "Общие параметры для всех стабилизаторов"))
        self.label_4.setText(_translate("Dialog", "Допустимое отклонение в точках коррекции, %"))
        self.label_7.setText(_translate("Dialog", "Допустимое отклонение для проверки линейности, %"))
        self.groupBox.setTitle(_translate("Dialog", "Стабилизатор 60 В"))
        self.label_5.setText(_translate("Dialog", "Напряжение, соответствующее 25 дискретам ЦАП, В"))
        self.label_6.setText(_translate("Dialog", "Напряжение, соответствующее 230 дискретам ЦАП, В"))
        self.groupBox_2.setTitle(_translate("Dialog", "Стабилизатор 200 В"))
        self.label_9.setText(_translate("Dialog", "Напряжение, соответствующее 25 дискретам ЦАП, В"))
        self.label_10.setText(_translate("Dialog", "Напряжение, соответствующее 230 дискретам ЦАП, В"))
        self.groupBox_3.setTitle(_translate("Dialog", "Стабилизатор 600 В"))
        self.label_13.setText(_translate("Dialog", "Напряжение, соответствующее 25 дискретам ЦАП, В"))
        self.label_14.setText(_translate("Dialog", "Напряжение, соответствующее 230 дискретам ЦАП, В"))
        self.groupBox_4.setTitle(_translate("Dialog", "Стабилизатор 4 В"))
        self.label_17.setText(_translate("Dialog", "Напряжение, соответствующее 25 дискретам ЦАП, В"))
        self.label_18.setText(_translate("Dialog", "Напряжение, соответствующее 230 дискретам ЦАП, В"))
        self.fixed_range_groupbox.setTitle(_translate("Dialog", "Фиксированный шаг"))
        self.verticalGroupBox_2.setWhatsThis(_translate("Dialog", "Относительный шаг устанавливается в процентах от максимума шкалы поверяемого прибора"))
        self.verticalGroupBox_2.setTitle(_translate("Dialog", "Относительный шаг"))
        self.label.setText(_translate("Dialog", "Точный, %"))
        self.label_2.setText(_translate("Dialog", "Обычный, %"))
        self.label_3.setText(_translate("Dialog", "Грубый, %"))
        self.save_and_exit_button.setText(_translate("Dialog", "Ок"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))
        self.save_button.setText(_translate("Dialog", "Принять"))
import icons
